version: '3.1'
services:
  rabbitamazonforwarder:
    build:
      context: .
    volumes:
      - ./config/mappings.json:/config/mappings.json
    ports:
      - "8080:8080"
    environment:
      MAPPING_FILE: /config/mappings.json
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}